site_name: MindCity-Wiki
theme: readthedocs

nav:
    - Home: 'index.md'
    - 'Technique':
        - 'Développeur': 'index_dev.md'
        - 'Mappeur': 'index_map.md'
    - 'MkDocs Tuto': 'tuto_mkdocs.md'